---
name: "dbt_package_template"
version: "0.0.1"

config-version: 2

require-dbt-version: [">=1.10.0"]

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
